use online_retail_dataset;

#1) how many customers are in the customers table

select count(*) from customers_data;

#2) how many orders are record in the order table

select count(*) from orders_data;

#3) display all customers from kochi

select CustomerName,city from customers_data where city = 'kochi';

#4) find the total sales from all orders

select round(sum(amount)) from orders_data;

#5) find the average order amount

select avg(amount) from orders_data;

#6)find the 10 most expensive products 

select product,max(amount) as expensive_product from orders_data 
group by product order by expensive_Product desc limit 10;

#7) find the total number of orders for each category,sorted highest to lowest

select category,count(*) as total_numbers from orders_data 
group by category order by total_numbers desc;

#8) find the total sales amount for each product, sorted from highest to lowest

select product,round(sum(amount)) as num_orders from orders_data 
group by product order by num_orders desc;

#9) find the number of orders placed using each payment method

select paymentMethod,count(*) as payment_method from orders_data 
group by PaymentMethod;

#10) find the total sales generated by each city

select c.city,round(sum(o.amount)) as total_sales from customers_data as c
inner join orders_data as o
on c.CustomerID = o.CustomerID
group by c.city;

#11) rank products by total revenue within each category using rank 

select Category,product,sum(amount) as total_revenue,
rank() over (partition by category order by sum(amount) desc) as Revenue_Rank from orders_data
group by category,product
order by category,Revenue_Rank;

#12) find customers who spent more than the average customer spend

select  * from orders_data
where amount>(select avg(amount) from orders_data);

#13) identify repeat (customers with more than 10 order)

select c.CustomerID,c.CustomerName,count(o.orderid) as order_count from customers_data as c
inner join orders_data as o
on c.CustomerID=o.CustomerID
group by c.CustomerID,c.CustomerName having count(o.orderid)>10
order by order_count desc;

#14) find top 10 customers based on toatal spending, displaying their name,city and total spending

select c.customername,c.city,c.customerID,sum(o.amount) as spending
from customers_data as c
inner join orders_data as o
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.CustomerName,c.City order by spending desc limit 10;

#15) find the monthly total sales and rank each month from highest to lowest

select month(orderdate) as month,sum(amount) as total_sale,
rank() over (order by sum(amount) desc) as sales_rank from orders_data
group by month(orderdate) order by sales_rank;

#16) create a view called monthly_sales_summery that a dashboard tool could read directly

create view monthly_sales_sumnmery as select month(OrderDate) as sales_month,
sum(amount) as total_sales,count(*) as total_orders
from orders_data group by month(orderdate)
order by month(orderdate);

#17) find customers who have placed at least 10 orders,displayinng their order count and total spending

select c.customerName,c.customerID,count(o.orderid) as order_count,
round(sum(o.amount)) as spendings
from customers_data as c
inner join orders_data as o
on c.CustomerID = o.CustomerID
group by c.CustomerName,c.CustomerID
having order_count >=10;

#18) write a stored procedure get_customer_history(customer_id) that returns a customer's full order history

DELIMITER //
create procedure get_customer_history(in customer_Id int)
begin
select c.customername,c.city,o.* from customers_data as c
join orders_data as o 
on c.customerID = o.CustomerID
where o.CustomerID = customer_Id 
order by orderdate desc;
end//
delimiter ;
call get_customer_history(1087);

#19) find the second highest spending customer in each city

select * from (select c.customerName,c.city,sum(o.amount) as spending,
rank()over(partition by city order by sum(o.amount) desc) as rnk
from customers_data as c 
join orders_data as o
on c.CustomerID = o.CustomerID
group by c.CustomerID,c.CustomerName,c.city) as spendings
where rnk = 2;

#20) product ranking within category for each category,find the top 2 products based on total sales.display:category,product,totalsales,rank

with top2 
as (select category,product,sum(amount) as tot_sales 
from orders_data group by category,product),
ranked as (select category,product,tot_sales,
rank() over (partition by category order by tot_sales desc) as rnk
from top2)
select category,product,tot_sales,rnk from ranked 
where rnk <=2;

